### ISSUE TITLE
Admin UGC page showing blank

### ISSUE THREAD

**Issue by Krupaly2k** [rinatkhaziev/wp-frontend-uploader#80]
Hi,

I am facing 2 issues using this plugin.

1. On Front, it is showing form fields twice.
2. On admin Media >> Manage UGC is showing blank for me.

I am using 4.8.1 version of wordpress. Please suggest me next step.

**Comment by rinatkhaziev** [comment]
@Krupaly2k What version of PHP you're using? What's your server software (nginx/Apache) and its version? Do you have access to error logs?

**Comment by tuanpht** [comment]
@rinatkhaziev I have same problem. Seems to it only happens on Windows server (XAMPP on Windows).

I debug the plugin and see the line https://github.com/rinatkhaziev/wp-frontend-uploader/blob/master/frontend-uploader.php#L686:
```php
if ( 0 === validate_file( $file ) ) {
	include_once $file;
}
```
Because `$file` in Windows is `E:\xampp\htdocs\....\plugins\frontend-uploader\lib\views\manage-ugc-media.tpl.php`, the function `validate_file( $file )` will return 2.

I think, we don't need use absolute path here:
```diff
- $file = FU_ROOT . "/lib/views/manage-ugc-{$view}.tpl.php";
+ $file = "lib/views/manage-ugc-{$view}.tpl.php";
```
Or see https://github.com/Automattic/amp-wp/pull/295.
What do you think?

**Comment by rinatkhaziev** [comment]
Wow, @tuanpht you're my hero! I got this reported a bunch of times over the years, and nobody followed up with the details, I don't use Windows so I was never able to reproduce it. I pushed a fix + added a little more verbosity to inform the user if template inclusion failed.

Thank you!

**Comment by tuanpht** [comment]
Thanks! You fixed it so fast.
Awesome plugin :+1:
